

 SELECT RESERV_DATE_FROM, RESERV_DATE_TO FROM HCR_T_RESERVATIONS Reserv where RESERV_ID = 39
 DECLARE 
	@RESERV_ID AS VARCHAR(10) = '39'

SELECT * FROM HCR_M_ASSETS
WHERE ASSET_SUBMODEL IN (
 SELECT DISTINCT ASSET.ASSET_SUBMODEL FROM HCR_M_ASSETS ASSET
 LEFT JOIN (SELECT Reserv.*, CarModel.MODEL_NAME FROM HCR_T_RESERVATIONS Reserv
			LEFT JOIN HCR_M_CARMODELS CarModel ON CarModel.MODEL_ID = Reserv.RESERV_CAR_TYPE
			WHERE CarModel.MODEL_ID = (SELECT RESERV_CAR_TYPE AS CarModel_ID FROM HCR_T_RESERVATIONS Reserv where RESERV_ID = @RESERV_ID)) RESERV_BY_ID ON RESERV_BY_ID.MODEL_NAME = ASSET.ASSET_SUBMODEL
 WHERE ASSET.ASSET_SUBMODEL = RESERV_BY_ID.MODEL_NAME
 AND ASSET.STATUS IN ('AVLBL', 'INUSE', 'PENDN')
 AND RESERV_BY_ID.RESERV_ID NOT IN (@RESERV_ID)
 AND (select RESERV_DATE_FROM from HCR_T_RESERVATIONS where RESERV_ID = @RESERV_ID) not between RESERV_BY_ID.RESERV_DATE_FROM AND RESERV_BY_ID.RESERV_DATE_TO
 AND (select RESERV_DATE_TO from HCR_T_RESERVATIONS where RESERV_ID = @RESERV_ID) not between RESERV_BY_ID.RESERV_DATE_FROM AND RESERV_BY_ID.RESERV_DATE_TO
 )


	