//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadExcel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MISC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReadExcel.Resources.MISC", typeof(MISC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string ActiveStatus_Active {
            get {
                return ResourceManager.GetString("ActiveStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string ActiveStatus_Inactive {
            get {
                return ResourceManager.GetString("ActiveStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveStatus.
        /// </summary>
        internal static string ActiveStatus_Type {
            get {
                return ResourceManager.GetString("ActiveStatus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string MainPlantStatus_No {
            get {
                return ResourceManager.GetString("MainPlantStatus_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPlantStatus.
        /// </summary>
        internal static string MainPlantStatus_Type {
            get {
                return ResourceManager.GetString("MainPlantStatus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string MainPlantStatus_Yes {
            get {
                return ResourceManager.GetString("MainPlantStatus_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        internal static string MTOCStatus_Active {
            get {
                return ResourceManager.GetString("MTOCStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string MTOCStatus_Delete {
            get {
                return ResourceManager.GetString("MTOCStatus_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D.
        /// </summary>
        internal static string MTOCStatus_Discontinues {
            get {
                return ResourceManager.GetString("MTOCStatus_Discontinues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I.
        /// </summary>
        internal static string MTOCStatus_Inactive {
            get {
                return ResourceManager.GetString("MTOCStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string MTOCStatus_Reactive {
            get {
                return ResourceManager.GetString("MTOCStatus_Reactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MTOCStatus.
        /// </summary>
        internal static string MTOCStatus_Type {
            get {
                return ResourceManager.GetString("MTOCStatus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string PlantStatus_Close {
            get {
                return ResourceManager.GetString("PlantStatus_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        internal static string PlantStatus_Open {
            get {
                return ResourceManager.GetString("PlantStatus_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string PlantStatus_Reopen {
            get {
                return ResourceManager.GetString("PlantStatus_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlantStatus.
        /// </summary>
        internal static string PlantStatus_Type {
            get {
                return ResourceManager.GetString("PlantStatus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleType.
        /// </summary>
        internal static string RoleType {
            get {
                return ResourceManager.GetString("RoleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string SupplyPlantStatus_No {
            get {
                return ResourceManager.GetString("SupplyPlantStatus_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SupplyPlantStatus.
        /// </summary>
        internal static string SupplyPlantStatus_Type {
            get {
                return ResourceManager.GetString("SupplyPlantStatus_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string SupplyPlantStatus_Yes {
            get {
                return ResourceManager.GetString("SupplyPlantStatus_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        internal static string UploadStatus_Complete {
            get {
                return ResourceManager.GetString("UploadStatus_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string UploadStatus_Error {
            get {
                return ResourceManager.GetString("UploadStatus_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string UploadStatus_Processing {
            get {
                return ResourceManager.GetString("UploadStatus_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string UploadStatus_Warning {
            get {
                return ResourceManager.GetString("UploadStatus_Warning", resourceCulture);
            }
        }
    }
}
