//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASHAOP_DEVEntities : DbContext
    {
        public ASHAOP_DEVEntities()
            : base("name=ASHAOP_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_M_Menu> C_M_Menu { get; set; }
        public virtual DbSet<L_InputOutput> L_InputOutput { get; set; }
        public virtual DbSet<L_SystemLog> L_SystemLog { get; set; }
        public virtual DbSet<L_Transaction> L_Transaction { get; set; }
        public virtual DbSet<M_AdditionalCondition> M_AdditionalCondition { get; set; }
        public virtual DbSet<M_AdditionalConditionCriteria> M_AdditionalConditionCriteria { get; set; }
        public virtual DbSet<M_AdditionalConditionHistory> M_AdditionalConditionHistory { get; set; }
        public virtual DbSet<M_AdditionalCriteriaName> M_AdditionalCriteriaName { get; set; }
        public virtual DbSet<M_AdditionalOperator> M_AdditionalOperator { get; set; }
        public virtual DbSet<M_Archeive> M_Archeive { get; set; }
        public virtual DbSet<M_CBULine> M_CBULine { get; set; }
        public virtual DbSet<M_Company> M_Company { get; set; }
        public virtual DbSet<M_Country> M_Country { get; set; }
        public virtual DbSet<M_CountryListModelPlant> M_CountryListModelPlant { get; set; }
        public virtual DbSet<M_CountryListModelType> M_CountryListModelType { get; set; }
        public virtual DbSet<M_CountryListModelTypeOfCountry> M_CountryListModelTypeOfCountry { get; set; }
        public virtual DbSet<M_CountryListTempCountry> M_CountryListTempCountry { get; set; }
        public virtual DbSet<M_CountryListTempList> M_CountryListTempList { get; set; }
        public virtual DbSet<M_CountryListTempModelType> M_CountryListTempModelType { get; set; }
        public virtual DbSet<M_CountryListTempRow> M_CountryListTempRow { get; set; }
        public virtual DbSet<M_CountryListUploadHistory> M_CountryListUploadHistory { get; set; }
        public virtual DbSet<M_CountryMapping> M_CountryMapping { get; set; }
        public virtual DbSet<M_CountryMappingDetail> M_CountryMappingDetail { get; set; }
        public virtual DbSet<M_DisplacementConfig> M_DisplacementConfig { get; set; }
        public virtual DbSet<M_Domain> M_Domain { get; set; }
        public virtual DbSet<M_Equipment> M_Equipment { get; set; }
        public virtual DbSet<M_FileManager> M_FileManager { get; set; }
        public virtual DbSet<M_Ki> M_Ki { get; set; }
        public virtual DbSet<M_LineCapacityOT> M_LineCapacityOT { get; set; }
        public virtual DbSet<M_Menu> M_Menu { get; set; }
        public virtual DbSet<M_Message> M_Message { get; set; }
        public virtual DbSet<M_MISC> M_MISC { get; set; }
        public virtual DbSet<M_Model> M_Model { get; set; }
        public virtual DbSet<M_ModelType> M_ModelType { get; set; }
        public virtual DbSet<M_ModelTypeEngine> M_ModelTypeEngine { get; set; }
        public virtual DbSet<M_ModelTypeEquipment> M_ModelTypeEquipment { get; set; }
        public virtual DbSet<M_ModelTypeTempEngine> M_ModelTypeTempEngine { get; set; }
        public virtual DbSet<M_ModelTypeTempEquipment> M_ModelTypeTempEquipment { get; set; }
        public virtual DbSet<M_ModelTypeTempRow> M_ModelTypeTempRow { get; set; }
        public virtual DbSet<M_ModelTypeTempSheet> M_ModelTypeTempSheet { get; set; }
        public virtual DbSet<M_ModelTypeTempType> M_ModelTypeTempType { get; set; }
        public virtual DbSet<M_ModelTypeUpload> M_ModelTypeUpload { get; set; }
        public virtual DbSet<M_PartMaker> M_PartMaker { get; set; }
        public virtual DbSet<M_Permission> M_Permission { get; set; }
        public virtual DbSet<M_Permissions> M_Permissions { get; set; }
        public virtual DbSet<M_Region> M_Region { get; set; }
        public virtual DbSet<M_Shipment> M_Shipment { get; set; }
        public virtual DbSet<M_User> M_User { get; set; }
        public virtual DbSet<M_UserRole> M_UserRole { get; set; }
        public virtual DbSet<M_UserRolePermission> M_UserRolePermission { get; set; }
        public virtual DbSet<M_YM> M_YM { get; set; }
        public virtual DbSet<PartDemandDetail> PartDemandDetails { get; set; }
        public virtual DbSet<PartDemandHeader> PartDemandHeaders { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<T_ComparePartKadai> T_ComparePartKadai { get; set; }
        public virtual DbSet<T_CompareProductionPlan> T_CompareProductionPlan { get; set; }
        public virtual DbSet<T_LogisticDayDetail> T_LogisticDayDetail { get; set; }
        public virtual DbSet<T_LogisticDayHeader> T_LogisticDayHeader { get; set; }
        public virtual DbSet<T_LogisticDayUploadDetail> T_LogisticDayUploadDetail { get; set; }
        public virtual DbSet<T_LogisticDayUploadHeader> T_LogisticDayUploadHeader { get; set; }
        public virtual DbSet<T_LogisticDayWiseDetail> T_LogisticDayWiseDetail { get; set; }
        public virtual DbSet<T_LogisticDayWiseHeader> T_LogisticDayWiseHeader { get; set; }
        public virtual DbSet<T_LogisticDayWiseUploadDetail> T_LogisticDayWiseUploadDetail { get; set; }
        public virtual DbSet<T_LogisticDayWiseUploadHeader> T_LogisticDayWiseUploadHeader { get; set; }
        public virtual DbSet<T_LogisticLeadtime> T_LogisticLeadtime { get; set; }
        public virtual DbSet<T_LogisticMonthDetail> T_LogisticMonthDetail { get; set; }
        public virtual DbSet<T_LogisticMonthHeader> T_LogisticMonthHeader { get; set; }
        public virtual DbSet<T_LogisticMonthUploadDetail> T_LogisticMonthUploadDetail { get; set; }
        public virtual DbSet<T_LogisticMonthUploadHeader> T_LogisticMonthUploadHeader { get; set; }
        public virtual DbSet<T_Maker> T_Maker { get; set; }
        public virtual DbSet<T_Part> T_Part { get; set; }
        public virtual DbSet<T_PartCapacityDetail> T_PartCapacityDetail { get; set; }
        public virtual DbSet<T_PartCapacityErrorRow> T_PartCapacityErrorRow { get; set; }
        public virtual DbSet<T_PartCapacityHeader> T_PartCapacityHeader { get; set; }
        public virtual DbSet<T_PartCapacityTemp> T_PartCapacityTemp { get; set; }
        public virtual DbSet<T_PartCapacityUploadHistory> T_PartCapacityUploadHistory { get; set; }
        public virtual DbSet<T_PartDemand> T_PartDemand { get; set; }
        public virtual DbSet<T_PartDemandFileUploadDetail> T_PartDemandFileUploadDetail { get; set; }
        public virtual DbSet<T_PartDemandFileUploadHeader> T_PartDemandFileUploadHeader { get; set; }
        public virtual DbSet<T_PartDemandTempUploadError> T_PartDemandTempUploadError { get; set; }
        public virtual DbSet<T_PartKadai> T_PartKadai { get; set; }
        public virtual DbSet<T_ProductionPlan> T_ProductionPlan { get; set; }
        public virtual DbSet<T_ProductionPlanAO> T_ProductionPlanAO { get; set; }
        public virtual DbSet<T_ProductionPlanAOMT> T_ProductionPlanAOMT { get; set; }
        public virtual DbSet<T_ProductionPlanAOMTDetail> T_ProductionPlanAOMTDetail { get; set; }
        public virtual DbSet<T_ProductionPlanAOOT> T_ProductionPlanAOOT { get; set; }
        public virtual DbSet<T_ProductionPlanAOSUBO> T_ProductionPlanAOSUBO { get; set; }
        public virtual DbSet<T_ProductionPlanCompare> T_ProductionPlanCompare { get; set; }
        public virtual DbSet<T_ProductionPlanDetail> T_ProductionPlanDetail { get; set; }
        public virtual DbSet<T_ProductionPlanMT> T_ProductionPlanMT { get; set; }
        public virtual DbSet<T_ProductionPlanMTTemp> T_ProductionPlanMTTemp { get; set; }
        public virtual DbSet<T_ProductionPlanMTTempDetail> T_ProductionPlanMTTempDetail { get; set; }
        public virtual DbSet<T_ProductionPlanPlant> T_ProductionPlanPlant { get; set; }
        public virtual DbSet<T_ProductionPlanReopen> T_ProductionPlanReopen { get; set; }
        public virtual DbSet<T_ProductionPlantAODownload> T_ProductionPlantAODownload { get; set; }
        public virtual DbSet<T_ProductionPlantDetailTemp> T_ProductionPlantDetailTemp { get; set; }
        public virtual DbSet<T_ProductionPlantDownload> T_ProductionPlantDownload { get; set; }
        public virtual DbSet<T_ProductionPlanUpload> T_ProductionPlanUpload { get; set; }
        public virtual DbSet<T_ProductionPlanUploadPlant> T_ProductionPlanUploadPlant { get; set; }
        public virtual DbSet<T_SUBO> T_SUBO { get; set; }
        public virtual DbSet<T_SUBOControlVersionDetail> T_SUBOControlVersionDetail { get; set; }
        public virtual DbSet<T_SUBOControlVersionHeader> T_SUBOControlVersionHeader { get; set; }
        public virtual DbSet<T_SUBOFileUploadDetail> T_SUBOFileUploadDetail { get; set; }
        public virtual DbSet<T_SUBOFileUploadHeader> T_SUBOFileUploadHeader { get; set; }
        public virtual DbSet<T_SUBOTempUploadError> T_SUBOTempUploadError { get; set; }
        public virtual DbSet<temp_GetUserDomain> temp_GetUserDomain { get; set; }
        public virtual DbSet<z_M_Function> z_M_Function { get; set; }
    }
}
