//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CountryListTempList
    {
        public int CountryListTempListID { get; set; }
        public int CountryListTempRowID { get; set; }
        public string YM { get; set; }
        public string ModelName { get; set; }
        public string Door { get; set; }
        public string Plant { get; set; }
        public string Version { get; set; }
    
        public virtual M_CountryListTempRow M_CountryListTempRow { get; set; }
    }
}
