//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CountryMappingDetail
    {
        public int CountryMappingDetailID { get; set; }
        public int CountryMappingID { get; set; }
        public int CountryID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual M_Country M_Country { get; set; }
        public virtual M_CountryMapping M_CountryMapping { get; set; }
    }
}
