//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CountryListModelTypeOfCountry
    {
        public int CountryListModelTypeOfCountryID { get; set; }
        public int CountryListModelTypeID { get; set; }
        public int CountryID { get; set; }
        public int CountryListModelPlantID { get; set; }
    
        public virtual M_Country M_Country { get; set; }
        public virtual M_CountryListModelPlant M_CountryListModelPlant { get; set; }
        public virtual M_CountryListModelType M_CountryListModelType { get; set; }
    }
}
