//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CountryListModelPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_CountryListModelPlant()
        {
            this.M_CountryListModelTypeOfCountry = new HashSet<M_CountryListModelTypeOfCountry>();
        }
    
        public int CountryListModelPlantID { get; set; }
        public Nullable<int> CountryListUploadHistoryID { get; set; }
        public int YMID { get; set; }
        public int ModelID { get; set; }
        public int CompanyID { get; set; }
        public string Version { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int MTOCStatusID { get; set; }
    
        public virtual M_Company M_Company { get; set; }
        public virtual M_CountryListUploadHistory M_CountryListUploadHistory { get; set; }
        public virtual M_Model M_Model { get; set; }
        public virtual M_YM M_YM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CountryListModelTypeOfCountry> M_CountryListModelTypeOfCountry { get; set; }
    }
}
