//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_CountryListTempRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_CountryListTempRow()
        {
            this.M_CountryListTempCountry = new HashSet<M_CountryListTempCountry>();
            this.M_CountryListTempList = new HashSet<M_CountryListTempList>();
            this.M_CountryListTempModelType = new HashSet<M_CountryListTempModelType>();
        }
    
        public int CountryListTempRowID { get; set; }
        public int CountryListUploadHistoryID { get; set; }
        public int RowNumber { get; set; }
        public string ErrorDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CountryListTempCountry> M_CountryListTempCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CountryListTempList> M_CountryListTempList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CountryListTempModelType> M_CountryListTempModelType { get; set; }
        public virtual M_CountryListUploadHistory M_CountryListUploadHistory { get; set; }
    }
}
