//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Menu()
        {
            this.M_Permission = new HashSet<M_Permission>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> ParentMenuID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string MenuLink { get; set; }
        public string Description { get; set; }
        public string IconName { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Permission> M_Permission { get; set; }
    }
}
