//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ModelTypeTempEngine
    {
        public int ModelTypeTempDetailID { get; set; }
        public int ModelTypeTempRowID { get; set; }
        public string SS { get; set; }
        public string DISP { get; set; }
        public string COMCARB { get; set; }
        public string Grade { get; set; }
        public string Mis { get; set; }
        public string ModelCode01 { get; set; }
        public string ModelCode02 { get; set; }
        public string ModelCode03 { get; set; }
        public string ModelCode04 { get; set; }
        public string ModelCode05 { get; set; }
    
        public virtual M_ModelTypeTempRow M_ModelTypeTempRow { get; set; }
    }
}
