//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ModelTypeEngine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ModelTypeEngine()
        {
            this.M_ModelTypeEquipment = new HashSet<M_ModelTypeEquipment>();
        }
    
        public int ModelTypeEngineID { get; set; }
        public int ModelTypeID { get; set; }
        public string ModelUsed { get; set; }
        public string ModelGPSP { get; set; }
        public string SS { get; set; }
        public int DISP { get; set; }
        public string COMCARB { get; set; }
        public string GRADE { get; set; }
        public string MIS { get; set; }
        public string ModelCode01 { get; set; }
        public string ModelCode02 { get; set; }
        public string ModelCode03 { get; set; }
        public string ModelCode04 { get; set; }
        public string ModelCode05 { get; set; }
        public int ModelTypeID1 { get; set; }
        public string ModelCode { get; set; }
    
        public virtual M_ModelType M_ModelType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ModelTypeEquipment> M_ModelTypeEquipment { get; set; }
    }
}
