//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ModelTypeTempSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ModelTypeTempSheet()
        {
            this.M_ModelTypeTempRow = new HashSet<M_ModelTypeTempRow>();
        }
    
        public int ModelTypeTempSheetID { get; set; }
        public int ModelTypeUploadID { get; set; }
        public int SheetNo { get; set; }
        public string YM { get; set; }
        public string Model { get; set; }
        public string Door { get; set; }
        public string Plant { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ModelTypeTempRow> M_ModelTypeTempRow { get; set; }
        public virtual M_ModelTypeUpload M_ModelTypeUpload { get; set; }
    }
}
