//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ModelTypeTempRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_ModelTypeTempRow()
        {
            this.M_ModelTypeTempEngine = new HashSet<M_ModelTypeTempEngine>();
            this.M_ModelTypeTempEquipment = new HashSet<M_ModelTypeTempEquipment>();
            this.M_ModelTypeTempType = new HashSet<M_ModelTypeTempType>();
        }
    
        public int ModelTypeTempRowID { get; set; }
        public int ModelTypeTempSheetID { get; set; }
        public int RowNo { get; set; }
        public string PNo { get; set; }
        public string VIN { get; set; }
        public string ErrorMessage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ModelTypeTempEngine> M_ModelTypeTempEngine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ModelTypeTempEquipment> M_ModelTypeTempEquipment { get; set; }
        public virtual M_ModelTypeTempSheet M_ModelTypeTempSheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_ModelTypeTempType> M_ModelTypeTempType { get; set; }
    }
}
