//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ModelTypeTempEquipment
    {
        public int ModelTypeTempEquipmentID { get; set; }
        public int ModelTypeTempRowID { get; set; }
        public string EquipmentName { get; set; }
        public string EquipmentValue { get; set; }
        public int Sequence { get; set; }
    
        public virtual M_ModelTypeTempRow M_ModelTypeTempRow { get; set; }
    }
}
