//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PartMaker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_PartMaker()
        {
            this.PartDemandDetails = new HashSet<PartDemandDetail>();
            this.T_PartCapacityDetail = new HashSet<T_PartCapacityDetail>();
        }
    
        public int PartMakerID { get; set; }
        public int CompanyID { get; set; }
        public string PartNumber { get; set; }
        public string MakerCode { get; set; }
    
        public virtual M_Company M_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartDemandDetail> PartDemandDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartCapacityDetail> T_PartCapacityDetail { get; set; }
    }
}
