//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_User
    {
        public int UserID { get; set; }
        public string Username { get; set; }
        public int DomainID { get; set; }
        public string Initial { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Company { get; set; }
        public string Department { get; set; }
        public string PlantLocation { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public int CompanyID { get; set; }
        public int UserRoleID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual M_Company M_Company { get; set; }
        public virtual M_Domain M_Domain { get; set; }
        public virtual M_UserRole M_UserRole { get; set; }
    }
}
