//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticLeadTimeMonthTempSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_LogisticLeadTimeMonthTempSheet()
        {
            this.T_LogisticLeadTimeMonthTempRow = new HashSet<T_LogisticLeadTimeMonthTempRow>();
        }
    
        public int LogisticLeadTimeMonthTempSheetID { get; set; }
        public int LogisticLeadTimeMonthUploadID { get; set; }
        public int SheetNo { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Ki { get; set; }
        public string CompanyName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LogisticLeadTimeMonthTempRow> T_LogisticLeadTimeMonthTempRow { get; set; }
        public virtual T_LogisticLeadTimeMonthUpload T_LogisticLeadTimeMonthUpload { get; set; }
    }
}
