//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticDayWiseDetail
    {
        public int LogisticDayWiseDetailID { get; set; }
        public int LogisticDayWiseHeaderID { get; set; }
        public Nullable<int> RowNo { get; set; }
        public string SupplyRegion { get; set; }
        public string SupplyPlant { get; set; }
        public string ReceiveRegion { get; set; }
        public string ReceivePlant { get; set; }
        public string Shipment { get; set; }
        public string ReceiveMonth { get; set; }
        public Nullable<int> WorkingDayTotal { get; set; }
        public string SupplyMonth1 { get; set; }
        public string SupplyMonth2 { get; set; }
        public string SupplyMonth3 { get; set; }
        public Nullable<int> WorkingDay1 { get; set; }
        public Nullable<int> WorkingDay2 { get; set; }
        public Nullable<int> WorkingDay3 { get; set; }
        public string ErrorMessage { get; set; }
    }
}
