//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticLeadTimeMonthUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_LogisticLeadTimeMonthUpload()
        {
            this.T_LogisticLeadTimeMonth = new HashSet<T_LogisticLeadTimeMonth>();
            this.T_LogisticLeadTimeMonthTempSheet = new HashSet<T_LogisticLeadTimeMonthTempSheet>();
        }
    
        public int LogisticLeadTimeMonthUploadID { get; set; }
        public int LogisticLeadTimeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public int UploadVersion { get; set; }
        public Nullable<int> I_LTPath { get; set; }
        public string I_LTFileNameOriginal { get; set; }
        public string I_LTFileNameSystem { get; set; }
        public Nullable<int> I_LTResultPath { get; set; }
        public string I_LTResultFileName { get; set; }
        public int UploadStatusID { get; set; }
        public string Result { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual M_Company M_Company { get; set; }
        public virtual M_FileManager M_FileManager { get; set; }
        public virtual M_FileManager M_FileManager1 { get; set; }
        public virtual T_LogisticLeadTime T_LogisticLeadTime { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LogisticLeadTimeMonth> T_LogisticLeadTimeMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LogisticLeadTimeMonthTempSheet> T_LogisticLeadTimeMonthTempSheet { get; set; }
    }
}
