//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticLeadTimeMonthKi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_LogisticLeadTimeMonthKi()
        {
            this.T_LogisticLeadTimeMonthDetail = new HashSet<T_LogisticLeadTimeMonthDetail>();
        }
    
        public int LogisticLeadTimeMonthKi { get; set; }
        public int LogisticLeadTimeMonthID { get; set; }
        public int Ki { get; set; }
    
        public virtual T_LogisticLeadTimeMonth T_LogisticLeadTimeMonth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_LogisticLeadTimeMonthDetail> T_LogisticLeadTimeMonthDetail { get; set; }
    }
}
