//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticMonthUploadDetail
    {
        public int LogisticMonthUploadDetailID { get; set; }
        public int LogisticMonthUploadHeaderID { get; set; }
        public int RowNo { get; set; }
        public string ExportRegion { get; set; }
        public string ExportPlant { get; set; }
        public string ImportRegion { get; set; }
        public string ImportPlant { get; set; }
        public string Shipment { get; set; }
        public Nullable<int> Ocean { get; set; }
        public int Inland { get; set; }
        public int Total { get; set; }
        public string ErrorMessage { get; set; }
    }
}
