//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LogisticLeadTimeMonthDetail
    {
        public int LogisticLeadTimeMonthDetailID { get; set; }
        public int LogisticLeadTimeMonthKi { get; set; }
        public Nullable<int> ImportRegion { get; set; }
        public string ImportPlant { get; set; }
        public string ShipAir { get; set; }
        public int OceanLT { get; set; }
        public int InlandLT { get; set; }
    
        public virtual T_LogisticLeadTimeMonthKi T_LogisticLeadTimeMonthKi { get; set; }
    }
}
