//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartCapacityDetail
    {
        public int PartCapacityDetailID { get; set; }
        public int PartCapacityHeaderID { get; set; }
        public int PartMakerID { get; set; }
        public Nullable<int> ExclusiveCommon { get; set; }
        public Nullable<double> LT { get; set; }
        public int Ki { get; set; }
        public int CapMonth { get; set; }
        public Nullable<int> PlannedVol { get; set; }
        public Nullable<int> StdCap { get; set; }
        public Nullable<int> MaxCap { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual M_PartMaker M_PartMaker { get; set; }
        public virtual T_PartCapacityHeader T_PartCapacityHeader { get; set; }
    }
}
