//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartDemandFileUploadDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PartDemandFileUploadDetail()
        {
            this.T_PartDemand = new HashSet<T_PartDemand>();
            this.T_PartDemandTempUploadError = new HashSet<T_PartDemandTempUploadError>();
        }
    
        public int UploadDetailID { get; set; }
        public int UploadHeaderID { get; set; }
        public Nullable<int> FileManagerID { get; set; }
        public string FileNameOriginal { get; set; }
        public Nullable<int> UploadStatus { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> SuccessRecords { get; set; }
        public Nullable<int> FailRecords { get; set; }
        public Nullable<System.DateTime> ProcessStart { get; set; }
        public Nullable<System.DateTime> ProcessEnd { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> ProcessStatusID { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string CancelBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartDemand> T_PartDemand { get; set; }
        public virtual T_PartDemandFileUploadHeader T_PartDemandFileUploadHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartDemandTempUploadError> T_PartDemandTempUploadError { get; set; }
    }
}
