//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartKadai
    {
        public int PartKadaiID { get; set; }
        public Nullable<int> ProductionPlanAOID { get; set; }
        public Nullable<int> AdditionalID { get; set; }
    
        public virtual M_AdditionalCondition M_AdditionalCondition { get; set; }
        public virtual T_ProductionPlanAO T_ProductionPlanAO { get; set; }
    }
}
