//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartCapacityErrorRow
    {
        public int PartCapacityErrorRowID { get; set; }
        public Nullable<int> PartCapacityUploadHistoryID { get; set; }
        public Nullable<int> RowNumber { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual T_PartCapacityUploadHistory T_PartCapacityUploadHistory { get; set; }
    }
}
