//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartDemandFileUploadHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PartDemandFileUploadHeader()
        {
            this.T_PartDemandFileUploadDetail = new HashSet<T_PartDemandFileUploadDetail>();
        }
    
        public int UploadHeaderID { get; set; }
        public int SeihanMonth { get; set; }
        public int SeihanYear { get; set; }
        public int Ki { get; set; }
        public int CompanyID { get; set; }
        public string FileType { get; set; }
        public int Version { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> SuccessRecords { get; set; }
        public Nullable<int> FailRecords { get; set; }
        public Nullable<int> MainProcessStatusID { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartDemandFileUploadDetail> T_PartDemandFileUploadDetail { get; set; }
    }
}
