//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartCapacityUploadHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PartCapacityUploadHistory()
        {
            this.T_PartCapacityErrorRow = new HashSet<T_PartCapacityErrorRow>();
            this.T_PartCapacityTemp = new HashSet<T_PartCapacityTemp>();
        }
    
        public int PartCapacityUploadHistoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SeihanMonth { get; set; }
        public Nullable<int> SeihanYear { get; set; }
        public Nullable<int> FileManagerID { get; set; }
        public string FileName { get; set; }
        public string FileNameSystem { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<int> UploadStatus { get; set; }
        public Nullable<int> TotalRecords { get; set; }
        public Nullable<int> SuccessRecords { get; set; }
        public Nullable<int> FailRecords { get; set; }
    
        public virtual M_Company M_Company { get; set; }
        public virtual M_FileManager M_FileManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartCapacityErrorRow> T_PartCapacityErrorRow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartCapacityTemp> T_PartCapacityTemp { get; set; }
    }
}
