//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PartDemandTempUploadError
    {
        public int UploadDetailID { get; set; }
        public int FileLineNo { get; set; }
        public string ErrorMessage { get; set; }
    
        public virtual T_PartDemandFileUploadDetail T_PartDemandFileUploadDetail { get; set; }
    }
}
