//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanMTTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductionPlanMTTemp()
        {
            this.T_ProductionPlanMTTempDetail = new HashSet<T_ProductionPlanMTTempDetail>();
        }
    
        public int ProdutionPlanMTTempID { get; set; }
        public Nullable<int> ProductionPlanUploadID { get; set; }
        public string Plant { get; set; }
        public string SeihanMonth { get; set; }
        public Nullable<int> Ki { get; set; }
    
        public virtual T_ProductionPlanUpload T_ProductionPlanUpload { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanMTTempDetail> T_ProductionPlanMTTempDetail { get; set; }
    }
}
