//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductionPlan()
        {
            this.T_ProductionPlanAO = new HashSet<T_ProductionPlanAO>();
            this.T_ProductionPlanPlant = new HashSet<T_ProductionPlanPlant>();
            this.T_ProductionPlanReopen = new HashSet<T_ProductionPlanReopen>();
            this.T_ProductionPlanUpload = new HashSet<T_ProductionPlanUpload>();
        }
    
        public int ProductionPlanID { get; set; }
        public Nullable<int> SeihanMonth { get; set; }
        public Nullable<int> SeihanYear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanAO> T_ProductionPlanAO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanPlant> T_ProductionPlanPlant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanReopen> T_ProductionPlanReopen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanUpload> T_ProductionPlanUpload { get; set; }
    }
}
