//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanPlant
    {
        public int ProductionPlanPlantID { get; set; }
        public Nullable<int> ProductionPlanID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> UploadVersion { get; set; }
        public Nullable<int> AOVersion { get; set; }
        public Nullable<int> PlantStatus { get; set; }
    
        public virtual T_ProductionPlan T_ProductionPlan { get; set; }
    }
}
