//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductionPlanUpload()
        {
            this.T_ProductionPlanMTTemp = new HashSet<T_ProductionPlanMTTemp>();
            this.T_ProductionPlantDetailTemp = new HashSet<T_ProductionPlantDetailTemp>();
            this.T_ProductionPlanUploadPlant = new HashSet<T_ProductionPlanUploadPlant>();
        }
    
        public int ProductionPlanUploadID { get; set; }
        public Nullable<int> ProductionPlantID { get; set; }
        public string I_ProductionMTPath { get; set; }
        public string I_ProductionMTFile { get; set; }
        public string I_ProductionMTNextPath { get; set; }
        public string I_ProductionMTNextFile { get; set; }
        public string I_ProductionDetailPath { get; set; }
        public string I_ProductionDetailFile { get; set; }
        public string I_ProductionDetailNextPath { get; set; }
        public string I_ProductionDetailNextFile { get; set; }
        public string O_ProductionDetailFile { get; set; }
        public string O_ProductionMTPath { get; set; }
        public string O_ProductionDetailNextFile { get; set; }
        public string O_ProductionMTNextPath { get; set; }
        public string O_ProductionMTFile { get; set; }
        public string O_ProductionDetailPath { get; set; }
        public string O_ProductionMTNextFile { get; set; }
        public string O_ProductionDetailNextPath { get; set; }
        public string Result { get; set; }
        public Nullable<int> StatusFlagID { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    
        public virtual T_ProductionPlan T_ProductionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanMTTemp> T_ProductionPlanMTTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlantDetailTemp> T_ProductionPlantDetailTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanUploadPlant> T_ProductionPlanUploadPlant { get; set; }
    }
}
