//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductionPlanAO()
        {
            this.T_ComparePartKadai = new HashSet<T_ComparePartKadai>();
            this.T_ComparePartKadai1 = new HashSet<T_ComparePartKadai>();
            this.T_CompareProductionPlan = new HashSet<T_CompareProductionPlan>();
            this.T_CompareProductionPlan1 = new HashSet<T_CompareProductionPlan>();
            this.T_PartKadai = new HashSet<T_PartKadai>();
            this.T_ProductionPlanAOMT = new HashSet<T_ProductionPlanAOMT>();
            this.T_ProductionPlanAOMTDetail = new HashSet<T_ProductionPlanAOMTDetail>();
            this.T_ProductionPlanAOOT = new HashSet<T_ProductionPlanAOOT>();
            this.T_ProductionPlanAOSUBO = new HashSet<T_ProductionPlanAOSUBO>();
            this.T_ProductionPlanCompare = new HashSet<T_ProductionPlanCompare>();
            this.T_ProductionPlanCompare1 = new HashSet<T_ProductionPlanCompare>();
            this.T_ProductionPlantAODownload = new HashSet<T_ProductionPlantAODownload>();
        }
    
        public int ProductionPlanAOID { get; set; }
        public Nullable<int> ProductionPlanID { get; set; }
        public Nullable<int> Version { get; set; }
        public string DraftConsolidateBy { get; set; }
        public Nullable<System.DateTime> DraftConsolidateDate { get; set; }
        public string FinalConsolidateBy { get; set; }
        public Nullable<System.DateTime> FinalConsolidateDate { get; set; }
        public string O_ProductionPlantMTSubmitPath { get; set; }
        public string O_ProductionPlantMTSubmitFile { get; set; }
        public string O_ProductionPlantGraphPath { get; set; }
        public string O_ProductionPlantGraphFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ComparePartKadai> T_ComparePartKadai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ComparePartKadai> T_ComparePartKadai1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CompareProductionPlan> T_CompareProductionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CompareProductionPlan> T_CompareProductionPlan1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PartKadai> T_PartKadai { get; set; }
        public virtual T_ProductionPlan T_ProductionPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanAOMT> T_ProductionPlanAOMT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanAOMTDetail> T_ProductionPlanAOMTDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanAOOT> T_ProductionPlanAOOT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanAOSUBO> T_ProductionPlanAOSUBO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanCompare> T_ProductionPlanCompare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanCompare> T_ProductionPlanCompare1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlantAODownload> T_ProductionPlantAODownload { get; set; }
    }
}
