//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanUploadPlant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_ProductionPlanUploadPlant()
        {
            this.T_ProductionPlanDetail = new HashSet<T_ProductionPlanDetail>();
            this.T_ProductionPlanMT = new HashSet<T_ProductionPlanMT>();
            this.T_ProductionPlantDownload = new HashSet<T_ProductionPlantDownload>();
        }
    
        public int ProductionPlanUploadPlantID { get; set; }
        public Nullable<int> ProductionPlanUploadID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public Nullable<int> Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanDetail> T_ProductionPlanDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlanMT> T_ProductionPlanMT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ProductionPlantDownload> T_ProductionPlantDownload { get; set; }
        public virtual T_ProductionPlanUpload T_ProductionPlanUpload { get; set; }
    }
}
