//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanMTTempDetail
    {
        public int ProductionPlanMTTempDetailID { get; set; }
        public Nullable<int> ProductionPlanMTTempID { get; set; }
        public string AFRegion { get; set; }
        public string AFPlant { get; set; }
        public string Model { get; set; }
        public string MY { get; set; }
        public string CountryCode { get; set; }
        public string SaleCountry { get; set; }
        public string EngineType { get; set; }
        public Nullable<int> Displacement { get; set; }
        public string Head { get; set; }
        public string TMClass { get; set; }
        public string Drive { get; set; }
        public string MOTCAP { get; set; }
        public string KeyCode { get; set; }
        public string ModelCode { get; set; }
        public string TypeCode { get; set; }
        public string DummyKey { get; set; }
        public string Remark { get; set; }
        public string Temp01 { get; set; }
        public string HCode { get; set; }
        public Nullable<int> Apr { get; set; }
        public Nullable<int> May { get; set; }
        public Nullable<int> Jun { get; set; }
        public Nullable<int> Jul { get; set; }
        public Nullable<int> Aug { get; set; }
        public Nullable<int> Sep { get; set; }
        public Nullable<int> Oct { get; set; }
        public Nullable<int> Nov { get; set; }
        public Nullable<int> Dec { get; set; }
        public Nullable<int> Jan { get; set; }
        public Nullable<int> Feb { get; set; }
        public Nullable<int> Mar { get; set; }
        public Nullable<int> FirstHalf { get; set; }
        public Nullable<int> SecoundHalf { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual T_ProductionPlanMTTemp T_ProductionPlanMTTemp { get; set; }
    }
}
