//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlanReopen
    {
        public int ProductionPlanReopenID { get; set; }
        public Nullable<int> ProductionPlanID { get; set; }
        public Nullable<int> PlantID { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Version { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
    
        public virtual T_ProductionPlan T_ProductionPlan { get; set; }
    }
}
