//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductionPlantDownload
    {
        public int ProductionPlanDownloadID { get; set; }
        public Nullable<int> ProductionPlanUploadPlantID { get; set; }
        public string DownloadedBy { get; set; }
        public Nullable<System.DateTime> DownloadedDate { get; set; }
    
        public virtual T_ProductionPlanUploadPlant T_ProductionPlanUploadPlant { get; set; }
    }
}
