//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SUBO
    {
        public int SUBOID { get; set; }
        public int UploadHeaderID { get; set; }
        public int UploadDetailID { get; set; }
        public int ModelID { get; set; }
        public int TypeID { get; set; }
        public int DestinationID { get; set; }
        public int YM { get; set; }
        public string SEDFlow { get; set; }
        public Nullable<System.DateTime> StartUp { get; set; }
        public Nullable<System.DateTime> BuildOut { get; set; }
        public Nullable<bool> IsDiscon { get; set; }
        public Nullable<bool> IsASHUpdate { get; set; }
    }
}
