//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SUBOControlVersionDetail
    {
        public int ControlVersionDetailID { get; set; }
        public int ControlVersionHeaderID { get; set; }
        public int ConsolidateVersion { get; set; }
        public int AOUploadVersion { get; set; }
        public string ConsolidatedBy { get; set; }
        public Nullable<System.DateTime> ConsolidatedDate { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public string ReopennedBy { get; set; }
        public Nullable<System.DateTime> ReopennedDate { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsFinal { get; set; }
    }
}
