//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SUBOFileUploadHeader
    {
        public int UploadHeaderID { get; set; }
        public int SeihanMonth { get; set; }
        public int SeihanYear { get; set; }
        public int FileManagerID { get; set; }
        public string FileNameOriginal { get; set; }
        public string FileNameSystem { get; set; }
        public int UploadResult { get; set; }
        public string UploadedBy { get; set; }
        public System.DateTime UploadedDate { get; set; }
    }
}
