//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_M_Function
    {
        public int FunctionID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionName { get; set; }
        public string ControlName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> RoleTypeID { get; set; }
        public Nullable<int> RoleType { get; set; }
    }
}
